// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

/**
 * Returns true when the required Supabase environment variables are present.
 * Use this to guard Supabase-dependent code paths so the app can still render
 * an error message instead of crashing at import time.
 */
export function isSupabaseConfigured(): boolean {
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

// Lazily create the client so a missing env var doesn't crash the entire app
// at module-load time.
let _supabase: SupabaseClient<Database> | null = null;

/**
 * Return the Supabase client, creating it on first call.
 * Throws if the required env vars are missing — callers should guard with
 * `isSupabaseConfigured()` when they can handle the absence gracefully.
 */
export function getSupabase(): SupabaseClient<Database> {
  if (!_supabase) {
    if (!isSupabaseConfigured()) {
      throw new Error(
        'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file.',
      );
    }
    _supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!);
  }
  return _supabase;
}

/**
 * Convenience re-export.  Prefer `getSupabase()` in new code; this export
 * exists for backward compatibility with files that already import `supabase`.
 */
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    return Reflect.get(getSupabase(), prop, receiver);
  },
});